export const GET_PLACES = "GET_PLACES";
export const CLEAR_PLACES = "CLEAR_PLACES";
export const PLACES_ERROR = "PLACES_ERROR";

export const INIT_PARAMS = "INIT_PARAMS";
export const SET_CURRENT_PARAM_VALUE = "SET_CURRENT_PARAMS";
export const SET_MONTH = "SET_MONTH";
export const TOGGLE_PARAM = "TOGGLE_PARAM";
export const RESET_PARAMS_VALUE = "RESET_PARAMS_VALUE";
export const CLEAR_PARAMS_RANGE = "CLEAR_PARAMS_RANGE";
export const PARAMS_ERROR = "PARAMS_ERROR";
